services:
  fastapi:
    build: .
    container_name: restaurant_fastapi_container
    environment:
      DATABASE_URL: "sqlite+aiosqlite:////app/data/app.db"
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    command: uvicorn main_directory.main:app --host 0.0.0.0 --port 8001
    restart: unless-stopped